### ISSUE TITLE
Cloudflare challenge failed

### ISSUE THREAD

**Issue by 7235201** [terry3041/pyChatGPT#10]
raise ValueError(f'Cloudflare challenge failed: {self.driver.page_source}')
ValueError: Cloudflare challenge failed: <html lang="en-US"><head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">

**Comment by terry3041** [comment]
Try few more times. Sometimes the bypass fails for no reason.
Or consider using a proxy

**Comment by terry3041** [comment]
I have added a retry mechanism in v0.2.8. Please check and let me know if you have any questions.
