### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 109

### ISSUE THREAD

**Issue by Marow** [terry3041/pyChatGPT#102]
Hi, 

i get this error when running the script on my ubuntu server.
If i try install chromedriver or chromium-browser again, it says up to date. Whats the problem?

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:33627
from session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 108.0.5359.124
`

**Comment by uccollab** [comment]
That means the Chrome version you installed on Linux is < 109. Just update it and it will be fixed.
