### ISSUE TITLE
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain

### ISSUE THREAD

**Issue by nowindnowave** [terry3041/pyChatGPT#11]
api = ChatGPT(session_token, proxy='http://proxy.xxx.com:1111:xxx:xxx')  # specify proxy
If the agent has an account password, is this how it is used?
Error message:
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain

**Comment by terry3041** [comment]
Proxy with auth is not supported and will not be implemented at this time as `undetected_chromedriver` does not support it.
However, you can use something like [Tinyproxy](https://tinyproxy.github.io/) to forward your upstream proxy to a local one without auth.
