### ISSUE TITLE
Chrome installation not found

### ISSUE THREAD

**Issue by Pitaya0111** [terry3041/pyChatGPT#12]
![1670840911790](https://user-images.githubusercontent.com/120381819/207037542-1b3e98d9-bbaa-44d3-bf36-96a0ce65d1b8.jpg)

How can I solve this prob!

**Comment by terry3041** [comment]
Install Chrome as the error says.

**Comment by Pitaya0111** [comment]
I've installed chrome before I using google colab to type those instructions

**Comment by terry3041** [comment]
> I've installed chrome before I using google colab to type those instructions My default bownser is chrome

Your target machine (i.e. Google Colab) does not have a Chrome installation.
