### ISSUE TITLE
403 error, I suspect OpenAI have implemented some barrier?

### ISSUE THREAD

**Issue by floraldo** [terry3041/pyChatGPT#13]
My code used to run just fine, but now I'm getting a 403 error all the time. What could be the issue?

def chatGPT_response(prompt):
    
  session_token = "valide token"
  api = ChatGPT(session_token)
  print(prompt)

  resp = api.send_message(prompt)
  response = resp['message']
  
  print(response)
  return response

**Comment by terry3041** [comment]
> My code used to run just fine, but now I'm getting a 403 error all the time. What could be the issue?

What is your library version? OpenAI has implemented Cloudflare's anti-bot protection yesterday and the library cannot be used if you don't update.
