### ISSUE TITLE
How to get correct __Secure-next-auth.session-token and cant not run with __Secure-next-auth.session-token.1...

### ISSUE THREAD

**Issue by nelsontseng0704** [terry3041/pyChatGPT#14]
Hi terry3041,

Thanks for your beautiful API. When I trying to get token via OpenAI website, I only can get "__Secure-next-auth.session-token.1" or "__Secure-next-auth.session-token.0". There is no "__Secure-next-auth.session-token". I input the token in "__Secure-next-auth.session-token.1" and "__Secure-next-auth.session-token.0" and then run the notebook that doesn't works.

Thanks!!

**Comment by terry3041** [comment]
Sorry but I cannot reproduce the same error. Can you please include a screen capture of the `Cookie` tab?

**Comment by nelsontseng0704** [comment]
Thanks for reply. Here is the screen shot:

<img width="1703" alt="Screen Shot 2022-12-13 at 11 19 10 AM" src="https://user-images.githubusercontent.com/88030183/207425304-e2562b40-1cb7-46d5-906b-9be5719d6ffc.png">

**Comment by nelsontseng0704** [comment]
btw, I use my company account on chrome.

**Comment by terry3041** [comment]
Can you delete all cookies except the session token 0 and see if it triggers a reauthentication?
