### ISSUE TITLE
No such file or directory: 'Xvfb'

### ISSUE THREAD

**Issue by dmisselpython** [terry3041/pyChatGPT#15]
Hi Terry,
thanks for all the work on this.

I am trying to call the API from google colab but continue to receive the following error when running on Windows 10 or in ubuntu [gui is xfce4] I continue to receive the following error even though I have xvfb installed.
[xvfb is already the newest version (2:1.20.13-1ubuntu1~20.04.4).]

api = ChatGPT(session_token)

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/pyChatGPT/pyChatGPT.py in __get_cf_cookies(self, retry)
     95             try:
---> 96                 display = Display()
     97             except FileNotFoundError as e:

9 frames
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/pyChatGPT/pyChatGPT.py in __get_cf_cookies(self, retry)
     97             except FileNotFoundError as e:
     98                 if 'No such file or directory: \'Xvfb\'' in str(e):
---> 99                     raise ValueError(
    100                         'Headless machine detected. Please install Xvfb to start a virtual display: sudo apt install xvfb'
    101                     )

ValueError: Headless machine detected. Please install Xvfb to start a virtual display: sudo apt install xvfb

Thanks in advance,
Dennis

**Comment by cgarvie** [comment]
Same on mac, which I believe should not require xvfb.

**Comment by terry3041** [comment]
@dmisselpython @cgarvie Are you guys using the library on Google Colab?
If yes then please follow this: https://github.com/terry3041/pyChatGPT/#how-do-i-get-it-to-work-on-google-colab

**Comment by terry3041** [comment]
> Same on mac, which I believe should not require xvfb.

Headless detection fixed on version 0.3.2. Please have a look and let me know if you have any question.

**Comment by dmisselpython** [comment]
Hi Terry: thanks for all your help on this as I was able to get this working after a few days. User Error !!! Thanks for closing this out.
