### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='chat.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by fzp0424** [terry3041/pyChatGPT#16]
![image](https://user-images.githubusercontent.com/102568752/207248563-7a3b57d2-9418-4070-a8d7-8db148c8293a.png)

![image](https://user-images.githubusercontent.com/102568752/207248527-1a4a2cfc-de8d-4c74-aaa6-99cf1cd07cfb.png)

**Comment by terry3041** [comment]
Sorry but I can't reproduce this error. Update to the latest version of the library and try again.
