### ISSUE TITLE
WebDriverException: Message: unknown error: failed to change window state to 'minimized', current state is 'normal'

### ISSUE THREAD

**Issue by eaffe** [terry3041/pyChatGPT#20]
I am now getting this error in Google Colab as well as on my Ubuntu Machine (it worked flawlessly this afternoon):

WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1

WebDriverException                        Traceback (most recent call last)
[<ipython-input-18-363f784ce8b2>](https://localhost:8080/#) in <module>
      8 session_token = 'XX I deleted this XX'
      9 
---> 10 api = ChatGPT(session_token)  # auth with session token
     11 #api2 = ChatGPT([email='example@domain.com](mailto:email='example@domain.com)', password='password')  # auth with email and password
     12 #api3 = ChatGPT(session_token, conversation_id='some-random-uuid', parent_id='another-random-uuid')  # specify a conversation

5 frames
[/usr/local/lib/python3.8/dist-packages/pyChatGPT/pyChatGPT.py](https://localhost:8080/#) in __init__(self, session_token, email, password, auth_type, proxy, verbose)
     64         self.__verbose_print('Display:', 'DISPLAY' in os.environ)
     65         self.__verbose_print('Headless:', self.__is_headless)
---> 66         self.__init_browser()
     67 
     68     def __verbose_print(self, *args, **kwargs) -> None:

[/usr/local/lib/python3.8/dist-packages/pyChatGPT/pyChatGPT.py](https://localhost:8080/#) in __init_browser(self)
    129         # Ensure that the Cloudflare challenge is still valid
    130         self.__verbose_print('Ensuring Cloudflare challenge')
--> 131         self.__ensure_cf()
    132 
    133         # Open the chat page

[/usr/local/lib/python3.8/dist-packages/pyChatGPT/pyChatGPT.py](https://localhost:8080/#) in __ensure_cf(self, retry)
    269         self.driver.switch_to.new_window('tab')
    270         if not self.__is_headless:
--> 271             self.driver.minimize_window()
    272 
    273         # Get the Cloudflare challenge

[/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py](https://localhost:8080/#) in minimize_window(self)
    617         Invokes the window manager-specific 'minimize' operation
    618         """
--> 619         self.execute(Command.MINIMIZE_WINDOW)
    620 
    621     def print_page(self, print_options: Optional[PrintOptions] = None) -> str:

[/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py](https://localhost:8080/#) in execute(self, driver_command, params)
    442         response = self.command_executor.execute(driver_command, params)
    443         if response:
--> 444             self.error_handler.check_response(response)
    445             response["value"] = self._unwrap_value(response.get("value", None))
    446             return response

[/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py](https://localhost:8080/#) in check_response(self, response)
    247                 alert_text = value["alert"].get("text")
    248             raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 249         raise exception_class(message, screen, stacktrace)

WebDriverException: Message: unknown error: failed to change window state to 'minimized', current state is 'normal'
  (Session info: chrome=108.0.5359.71)

**Comment by terry3041** [comment]
Hi. May I know your environment?
This is most likely due to the headless environment detection in the code.

**Comment by eaffe** [comment]
Sorry, what do you mean by environment ? I encounter this error when executing the code in Google Colab as well as on my ubuntu machine. Python 3.8 in both cases

**Comment by terry3041** [comment]
> Sorry, what do you mean by environment ? I encounter this error when executing the code in Google Colab as well as on my ubuntu machine. Python 3.8 in both cases. I work with "xvfb-run -a python3 etc."

Just release v0.3.6. This problem should be fixed. Please check and let me know if you have any questions.

**Comment by eaffe** [comment]
Thanks for the update! I will check when my currently running script will be finished. 
I found  a working interim solution: I commented out those two lines in pyChatGPT.py:

270 if not self.__is_headless:
271 self.driver.minimize_window()

**Comment by terry3041** [comment]
> Thanks for the update! I will check when my currently running script will be finished. I found a working interim solution: I commented out those two lines in pyChatGPT.py:
> 
> 270 if not self.__is_headless: 271 self.driver.minimize_window()

Yeah thats what I did in the new release until I find a better solution.
