### ISSUE TITLE
Error When Message Contains Emoji

### ISSUE THREAD

**Issue by kimkimkeren** [terry3041/pyChatGPT#21]
```
api = pyChatGPT(session_token)
resp = api.send_message("Selamat pagi menuju siang😁")
api.close()
```

![image](https://user-images.githubusercontent.com/8066356/207480079-3130ce60-d29a-4c70-88a4-6f945c715644.png)

Maybe this solution works? https://stackoverflow.com/questions/59138825/chromedriver-only-supports-characters-in-the-bmp-error-while-sending-emoji-with

**Comment by terry3041** [comment]
Hi. The link you sent works in this situation. I have updated the library to v0.3.7. Please check and let me know if you have any questions.
