### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Phantom8015** [terry3041/pyChatGPT#22]
Each time I run, I get a 'list index out of range' error. That is actually all it gives me and in that exact format.

**Comment by terry3041** [comment]
This should be fixed by the latest commit. But I haven't pushed a new version.

**Comment by terry3041** [comment]
> Each time I run, I get a 'list index out of range' error. That is actually all it gives me and in that exact format.

Updated to v0.3.8. Please check and let me know if you still have any problems.
