### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by thuSunao** [terry3041/pyChatGPT#25]
I've got this problem in "api.send_message(msg)" function. How can I solve it?

**Comment by thuSunao** [comment]
> I've got this problem in "api.send_message(msg)" function. How can I solve it?

already upgraded to 0.3.8

**Comment by terry3041** [comment]
May I have the complete error log here?

**Comment by thuSunao** [comment]
Traceback (most recent call last):
  File "/home/sunao/sqa/models/run_gpt3.py", line 260, in <module>
    prediction, output = get_gpt3_result(prompt, args)  # 'A', ..., 'E'
  File "/home/sunao/sqa/models/run_gpt3.py", line 73, in get_gpt3_result
    res = response.send_message(prompt)
  File "/home/sunao/anaconda3/envs/sqa/lib/python3.10/site-packages/pyChatGPT/pyChatGPT.py", line 349, in send_message
    request = self.driver.find_elements(
IndexError: list index out of range

and the function is 
request = self.driver.find_elements(
            By.XPATH, "//div[starts-with(@class, 'request-:')]"
        )[-1]

**Comment by terry3041** [comment]
I cannot reproduce this error. Can you edit the site package like this and see if the error persist?
![image](https://user-images.githubusercontent.com/19218518/207555226-01e63999-cfc2-4a51-9f2a-650c64c3d222.png)

**Comment by thuSunao** [comment]
> I cannot reproduce this error. Can you edit the site package like this and see if the error persist?
> 
> ![image](https://user-images.githubusercontent.com/19218518/207555226-01e63999-cfc2-4a51-9f2a-650c64c3d222.png)

yes the error still persists.
but in v0.3.8 i found my code a little bit different from your pic
![image](https://user-images.githubusercontent.com/75597473/207557544-cdea0a91-e6d6-46b9-8aa3-ae1b716f57a0.png)

**Comment by terry3041** [comment]
> yes the error still persists. but in v0.3.8 i found my code a little bit different from your pic

Sorry my bad. I forgot to push new version. Now in your pic, can you swap the "Get response element" and "Wait for response" part and see the result?

**Comment by thuSunao** [comment]
> 

i swapped and sadly still got the same error 
and i tried to increase the sleep time from 0.25 to 1, but it still doesn't work

**Comment by eaffe** [comment]
> > 
> 
> i swapped and sadly still got the same error and i tried to increase the sleep time from 0.25 to 1, but it still doesn't work

same for me. 5 seconds doesn't help either

**Comment by thuSunao** [comment]
I run my code in Linux server, does it cause the problem?

**Comment by terry3041** [comment]
I think I found the problem but let me make sure before I make new commit.

**Comment by thuSunao** [comment]
thanks a lot!
