### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by 7235201** [terry3041/pyChatGPT#27]
when show long text, it will show network error,All text disappear
how to fix ,thks

**Comment by Phantom8015** [comment]
this is nothing wrong with the package, it is something with chatgpt.

**Comment by alcarazolabs** [comment]
According to chatgpt creators they are receiving a lot of request and they are trying to autoscalling this application with more servers. Chagpt is suffering his succesfull, also according his greators this type of application is money consuming. We need to take advantage of each answer and not waste time and compute power.
