### ISSUE TITLE
Suggestion, Not error

### ISSUE THREAD

**Issue by Phantom8015** [terry3041/pyChatGPT#29]
When the package is run, it opens a chat.openai.com/auth/session link. Instead of specifying a session token, why not grab it from that json response? The session token is labelled "acces_token" in the json.

**Comment by terry3041** [comment]
Do you mean to grab the session_token from that json response?
But does it do anything? A session_token will expire in 24 hours regardless of you updating the session_token from https://chat.openai.com/api/auth/session.

**Comment by Phantom8015** [comment]
ah sorry i meant to not use what the json gives but use something similar to the cf cookies for the session token cookie

**Comment by Phantom8015** [comment]
good point, ill try and find a way to get this to work, if I have your permission to edit the code.

**Comment by terry3041** [comment]
> good point, ill try and find a way to get this to work, if I have your permission to edit the code.

Sure, feel free to fork the repo and make a pull request if you find anything useful.
