### ISSUE TITLE
problem when send request with conversation_id

### ISSUE THREAD

**Issue by Jiroun** [terry3041/pyChatGPT#3]
I send first message normal
like something = ChatGPT(email=email, password=pas) 

and I want to continue in the same conversation so the second message I sent is like

something  = ChatGPT(email=email, password=pas, conversation_id=conversation_id)

but this returns error  {"detail":"Too many requests, please slow down"} 
even If I wait between the two messages

**Comment by terry3041** [comment]
Hi. To continue on the same conversation, you also need to provide a `parent_id`, which I forgot to leave as a parameter when initing the ChatGPT class.
Now I have correctly include that in v0.1.1 and you may check the README for the correct usage. Please let me know if you have any questions.
