### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by lsyysl9711** [terry3041/pyChatGPT#33]
Hello! 

I just type into two questions, one after another and it says "To many requests in one hour, Try again later". But I just try one problem!

Could you help me solve this problem?

Thanks,

**Comment by avenuetech** [comment]
Are you using the latest version of the package? I had a similar issue and i it got solved with the fixes in the latest release. May not be the same thing but still worth a try.

**Comment by eaffe** [comment]
I get this too.

**Comment by doevent** [comment]
Try waiting 60 sec
