### ISSUE TITLE
chatgpt add new verity

### ISSUE THREAD

**Issue by 7235201** [terry3041/pyChatGPT#36]
chatgpt add new verity ,now get session then cant login

**Comment by terry3041** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/19218518/208053578-e9df2a3d-3a23-4c8f-ad17-e75003b111e9.png)

**Comment by alcarazolabs** [comment]
Dear @terry3041 I will encourage you that should test the library in a ubuntu virtual machine. It seems be working fine on windows machines.

**Comment by terry3041** [comment]
> Dear @terry3041 I will encourage you that should test the library in a ubuntu virtual machine. It seems be working fine on windows machines.

I do have a headless ubuntu instance and I did not encounter any errors.
