### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by 7235201** [terry3041/pyChatGPT#40]
chatgpt delete result-: starts
I use
markdown prose break-words dark:prose-invert light
instead
its ok

**Comment by fzp0424** [comment]
![image](https://user-images.githubusercontent.com/102568752/208218899-b3c8845b-f4e8-4754-852e-e4d07f081714.png)
got the same error

**Comment by fzp0424** [comment]
> ![image](https://user-images.githubusercontent.com/102568752/208218899-b3c8845b-f4e8-4754-852e-e4d07f081714.png) got the same error

V0.3.9

**Comment by terry3041** [comment]
Check v0.3.9.4.

**Comment by fzp0424** [comment]
> Check v0.3.9.4.

it works now, thks
