### ISSUE TITLE
in send_message response = self.driver.find_elements( IndexError: list index out of range

### ISSUE THREAD

**Issue by Straxit0** [terry3041/pyChatGPT#55]
I don't understand this issue : 
i tried to do a new auth_type like #42
And i tried to update pyChatGPT like said in #52
But it doesn't fixed the issue

File "location of pyChatGPT ", line 395, in send_message
    response = self.driver.find_elements(
IndexError: list index out of range

Do someone has an idea of how to solve this please ?
Thaks guys ^^

**Comment by MidTano** [comment]
i fix this ;) wait update

**Comment by Straxit0** [comment]
> i fix this ;) wait update

Thank you very much ^^

**Comment by terry3041** [comment]
Should be fixed in v0.3.9.5.
