### ISSUE TITLE
Invalid Session Token

### ISSUE THREAD

**Issue by p-i-** [terry3041/pyChatGPT#57]
I'm playing with this on macOS.

```
api = ChatGPT(SESSION_TOKEN)
```

... gives the following:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 api = ChatGPT(SESSION_TOKEN)

File ~/code/2023/ML/hacking-chatGPT/.venv/lib/python3.11/site-packages/pyChatGPT/pyChatGPT.py:70, in ChatGPT.__init__(self, session_token, email, password, auth_type, proxy, verbose, window_size)
     68 self.__verbose_print('[0] Display:', 'DISPLAY' in os.environ)
     69 self.__verbose_print('[0] Headless:', self.__is_headless)
---> 70 self.__init_browser()

File ~/code/2023/ML/hacking-chatGPT/.venv/lib/python3.11/site-packages/pyChatGPT/pyChatGPT.py:135, in ChatGPT.__init_browser(self)
    133 # Ensure that the Cloudflare cookies is still valid
    134 self.__verbose_print('[init] Ensuring Cloudflare cookies')
--> 135 self.__ensure_cf()
    137 # Open the chat page
    138 self.__verbose_print('[init] Opening chat page')

File ~/code/2023/ML/hacking-chatGPT/.venv/lib/python3.11/site-packages/pyChatGPT/pyChatGPT.py:344, in ChatGPT.__ensure_cf(self, retry)
    342     self.__verbose_print('[cf] Authorization is empty')
    343     if not self.__auth_type:
--> 344         raise ValueError('Invalid session token')
    345     self.__login()
    346 self.__verbose_print('[cf] Authorization is valid')

ValueError: Invalid session token
```

Before erroring, it's opening up a Chrome window:

<img width="979" alt="Screenshot 2022-12-22 at 04 03 50" src="https://user-images.githubusercontent.com/693495/209053276-8620831a-b367-445e-8284-00eb00481029.png">

<img width="245" alt="Screenshot 2022-12-22 at 04 05 57" src="https://user-images.githubusercontent.com/693495/209053378-6f4206f2-a0ed-4c42-a845-156c94b9fa2a.png">

<img width="375" alt="Screenshot 2022-12-22 at 04 06 12" src="https://user-images.githubusercontent.com/693495/209053408-6e8bcc16-ab78-4949-bfa6-c41bb3c43d96.png">

Now my SessionToken is 100% correct.  It's the cookie value for key `intercom-session-dgkjq2bp`.

PS Arriving from https://www.youtube.com/watch?v=lBCoktYvSKg&ab_channel=BhaveshBhatt
PPS You don't have a Discord do you?

**Comment by terry3041** [comment]
> Now my SessionToken is 100% correct. It's the cookie value for key `intercom-session-dgkjq2bp`.

Now I can tell you that `session_token` is 100% incorrect. Please check README for grabbing a correct one.
