### ISSUE TITLE
Can we use beautiful supe instade of selenium

### ISSUE THREAD

**Issue by sushen** [terry3041/pyChatGPT#58]
to send a request every time it's bringing the browser that can't be good.

if there is now API on the list there can be a proper request-sending situation.

Its bring Browser.
![image](https://user-images.githubusercontent.com/4492335/209121537-2cfc71da-4ec8-4da1-ab1a-7e699d2f8371.png)

and There is x path problem too.
![image](https://user-images.githubusercontent.com/4492335/209121560-a6e95c44-e217-47f6-9371-061b4cae783a.png)

**Comment by terry3041** [comment]
> Its bring Browser. 

Well its due to the Cloudflare protection. Its probably the best solution so far.
If you want a better one, ask CF and don't ask me.

> and There is x path problem too.

I am trying to fix this. Please try the latest version and see if it works.
