### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by liquidpeachy** [terry3041/pyChatGPT#59]
I'm using the most recent version pyChatGPT (the one updated 11 hours ago).

I'm getting the following error. Note, this error doesn't happen every time. Maybe 50% of the time.

Error:
`line 606, in send_message   
    response = self.driver.find_elements(
IndexError: list index out of range`

Anyone know why it's happening?

**Comment by terry3041** [comment]
This is the issue that bother me for long time. But I still don't know how to fix this.
Try v0.3.9.6.

**Comment by DevRoss** [comment]
Analyse as below:
The tags are `<ul>` and `<li>` tags when the response is a list, so xpath '//div[@class="flex-1 overflow-hidden"]//div[p]' does not work (whill raise `IndexError: list index out of range`), while using '//div[starts-with(@class, "markdown prose w-full break-words")]'  is better. (see fig1)

**However**, the tag is `<p>` when the response is an error with red text,  the class name no longer contains 'markdown prose w-full break-words', this will pass the red text checking, and  the `send_message`  function will return the last valid response as the current response.

![image](https://user-images.githubusercontent.com/14539186/209444417-08352637-5d50-4f26-82f3-9b1f38f0cd81.png)

![image](https://user-images.githubusercontent.com/14539186/209444564-efcfd951-28ca-4c9b-807c-24c8d4539142.png)

**Comment by terry3041** [comment]
Just released v0.4.0. Ty @DevRoss.
