### ISSUE TITLE
Cloudflare issue 

### ISSUE THREAD

**Issue by BooBooKittyFck** [terry3041/pyChatGPT#6]
Hello Terry 
Thanks for your work - it seemed like they now using Cloudflare any chance you could do a bypass or something? 
Or is it just me ran into the Cloudflare issue?

```
</div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
```

**Comment by magicmars35** [comment]
Tyey just add a challenge at the main page  :
I believe all unofficial APIs are now down ...

`<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            chat.openai.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=77816379cc6722a3')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            chat.openai.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/auth/session?__cf_chl_f_tk=mgs1BQ5KlKESJXiyWb4j0yLo0itjqsXXXXXXXXXXXXXXX0-0-gaNycGzNEpE" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="HPC5UPhC8URSRf7yXSjyalsYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXRjTIySvQh4yaw-Igv9KCo-Cfdmm7IBFe2m-8j81sCbtA5Z1ntwm1jsqAassXwKpdqrEhh-e1j5xN_TIjGNWY0IM369OE51uy9e71AuX-SYSfCon8V6-lTN-OfI9HyKXJNYeHxx92pHiFjQNFeyuUysglzDSs-y9Di1r9FdghsqFenejkTfziwAcsPccjMh_4kr-UGVt7ZtbjQ3JIWpYVbjY4j6IfKwLjNin1qVz9BUwCpdVPtjIFbwEHWu_lnUtGMkex549rIG3kXfPva_dnSy81kJuPNu3TmEvLTsXKoy723f7ZYLzmhXgnNU_VMYhCCwWWI-7q2VwAwhTLFeKU5dEiuShKvg36Ofx7GyvEitHTC27BE9iShVpg5qTrkwQAzKfd4osz-TWGTqiIZrVQYir2shwt_VOJtUoFZwSjdVYrPwRZ1izINWmcUgceueh4Nl7tUSqpyjEA1DrIcEffD16ByA6sknuXO7ruCIMzWpHyXbbRM_UTDJxIA80bxggrCLuQXFMdZxOV00EO6s2yEiPeRt8P55vujK8vWvlEUugWYNIvd6OGdf7VtajLhhklDiVOuiFpBJYcUPKBC_hJVCE5BIfMtdPmpX7hK3inMOQ1g1IuYyHdFxgSqGcHwO1hCsHo6Ivmmp6XquHQ5jqqlfkhPuKiBqg">
            <input type="hidden" name="r" value="I1nxy8Ro5hpamYEpZEdH1Si0TxA5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5s2Yo7VtoLQHDBOyeK1TdPAmv436yc0m67dmwlUNhi9SreyB4h8WQ0uBiueF29vj89yVWUkAsWectZxSdgGS76BVtVpTy2U7LA69WNB92K6gJY7RmBSYUdAX+VI8Ks1ElxdTYKNnDfOgsU8Rvy/552aXLd2STab+1k5BWNv7i2LLrys6BvxXCz9E02az3EnvYFItj9rUaRv5eZ6zHXaXvDvO5XUl9b3fdNt0IhFuG3+cYdpnnDiqAiymzT6uBmKgZayzgkjW2uxC7jOsZyTrrcXGCUMTY/I7mEFIZ8FMWpaxpiKbFi2sIhDP3Eo76RAHdJB4u478uB7/o/qShCQYWJyLpU4RPfF2E4yGahHbVkvrfcpfjur8NedjJqOV5bxjbI+iUs5BqbLdhoUyfuu7FbdO0UvbFjkRIUnaKjXyBsqEet8fhdsiKLvTrnrnODJ1pX93W/+QmnkBrxfJUhW+Kkn1IdN0j/IYrjxcRCMJCv+eYm3V65KEem9QEYKWeN9p6D4IjFxygdNw6o0DX1stn/yuQDyLKc0JMjdoop3taIewE6EUJ+O57DL0MaDsYppMrQm0ktREO7RNUCwrQEEcpH2/fQZS8TMp6dJD+wiuZI8r7tkF/kyCsWUObURQlVckficWoVRDHXlAia59rIiY4bIn3V370jzPjdA3IGMQlVNT+wVmK5ibGDM107h9j9Two+ySuzkVMtPU8KBXxMTBf6/xMRZhtBHMGVvi7PmqBaw2iXsTlDlljs9jGjpg3MEaGlxly7o+1YfgtgysRoFKGIH7DzKohKEUCjwpfZ2VSnYv6UmYjqEMeUbtKSa1krmYXUVrRqTAdl1RxKVlBZ2rFwO6AneyVRL0XTqnrlHUXdjNAb0y+u9lfr7q4nBz1z3WjjOXDsnD/OvkRFtzgkYu/HvTBBfZNXGkULJY5KPappHRIuaPn+u/hSSMiHwM/HFuJKhORiTs3IdwGg/a3H8GL5HF2Rcva5JOPZh5gFgeU0cNf8RmzOIKwnp53JwOyx4ccJj+xj8Hla7aRNLMNJS+1r11VG26+hhAbjUTme1UbcfFPDg2wwM9TeA7OAZF0kj2AoJaKbPfJi0MSWkGMWng97erwCPk84gTY9RTl8bIPsByixldo0BeKvAV3+QdV+eabrivZWIvCWObsP3to/zQyFUIlWjrICQPhyx4mRm9oI2kmq/AmLcY340n5V4uthDbK+6a4bXukJGk3jqefgvR/Ay0+U9RFSwQZhWlhA2p36EWiY8CKdH7VPiC1frG3knZxKTNkwCgwfFByoe9vn86BIctGbDBwd1V6wYVjK0265H7Xygd+5PicKuR8X1Lx5XPDLDJv8oNUJOfxyrXa0GI8StWsREQup9GRtWddGoIDKLZukzUEANkTT3CSGKwUnrA1FygyeMtLKY/NjgSALOYRX3EmcnsaGtPWk28ZhePCnhDZqb/URDfSDGnhgxZ5nND1ELGzZzauM5nKk+yaALSzZrpPWDkjLjUCbIqSCDLewP/32MP6t0O3hxu7YV5epCjI+eAqxPqVryDFpo7jpybdaxfS1dnPGu/D1V3sun9SRMbACElFSWDHDXUoN4TYiE0VBjtehr9d9xDxHGCdVuhuXG6IgtzlHLMV9iueEia/ljqhS1zf9xlTBB6uo338fOhTLVikQA2SOsfA+b0zHGtyBtpnes6EZv1K3TuiryASfGw5y1fzdCY3bQYnxviHgmSnlcyLO0jYFI8CGBX13JRU6HVF4SF02P65sk8R9aWGab2H/ElTqKB6fnWgNcx1JygGnjThWbSCmzs095V6T6yTQOooquL2pnb+X+PhuJMZWftMW3keJV832UmFbjWqiWhzT5MIkEPR+tVcp2+kSPQG+8skjZKbP3AHa3YbDGbpmYOU6wzlJERuRCBQWDXmtbLxlH+Bnh8BbpHwGnRwIf2benIxS0YEy0l8DJAGDEDQmyefiJSMKWWlKhDjwjfirjBhc8jmtyy8eC3fizflFKN9qwdF38f/w5Wt8zCJupeSkJAPDhvvN5Xgac5dyArX6/Y22I3wHAqSJE34sZAPzKHlpSoNdvoPoUX1vumC3kAseJZHI1BftKm4o8ExRopif77TqvRVp43e67XknFuBy2NLaX6hmgWYbj6zfE3+UDN4MG/1OyQCwvgEkIk/fo9vEfV10yGCPyWYVHoWIMmoQ5/+XdeB0Yrw4hz1XWKoI5RocA/veh16sCgMgRgcdguMDvXMXDhidflRAhnpNMHUfZXp5/g3/hWaEkNVqOs15Mc9ypHsKnGyl58OwWfn9E19bZu/pTQ4vDI8Eho+kM16YHdLOhFZ2A4djSPJT4y03is41zwMGPckLO9bohntgjZGn8j3j0kkYvei1YByVN2LvvU4o2xVfdnfJHZbzck8kA8Y8gZMkQQ4z8rm//WiC7eiIy98/Myo8njOo/8jZbT2aF4bJ6Mem7MF4QCAwWiX1gVogbzdBV7sHRo0oSRiWsRkTwfbPX0EEvQzDNfNoQQ2TW6TyAFbEx+E6Czf0K1z0+CxxIeYKWkFUTU9O7pg74OvZbpD+bU3a0B0m+qb/rT9oXkcGnwnRTxxWOmVrJpNOSlW79PLogE+uoc4Ff0r/tRH5nFMaCKIczWJs72g95cmEikV4631c2GSxgVW1DBEMvy2bAfW0KTW776yuaWNntVoWAMzlL31K6rJkq6x478uPaPHVy0KnUZ7STCaHA/o6lI1pWMt6zyn6yu4XhwrsR24rO1KlbLG5TZJUOEtFaGg+sR7Ke5L9Q2CJYIxds3RNeTl/StQfD3zQp3Blax6MaNrvp2sbQzueioSTH3J5OHvjyaHPkqgloz0PfoZJU5fvrs8gSSZxjo2pv9dxjiXMW3LM9Ty4z3lCJnocoi8v2ngeazuMrFQ8+m7GE3yfQtvagQ7hXeJ0FFDsIpAgCfllxxckPd7rsYZXu8yyplciQBPe/Z9N7qDRRVVtiRxeVGcU18K7fr/B8/KH79kr6rYUn1pRjTXGUUcOeYNG3hJuf/cGXpnbztMZ3BgRhvK4zyhPwO57wU6NtKOOW/If3g8fgzOifGSASl0YjbYccTUAycTM9zIYXSEb/Bgujd72ycLedRA0gVEfpfEce+US7W2HQyElmQ35DBYyjHdUBUxuixMzgs/zec6uLp8E/xuQ6muH2TWlfcFohnyPgY+ULmdMbwQjmdDP7/mMczQC6bgiJNo5p/O25S8Xyaz+K/UqpBJzhPYf99gQyLPvUGyntO1+C4Wn6FGGxBBVWli5OXitMiJW7wg37bEXx9ON4ZfNrBaH0lhTonadR2sY+iqoE0MlTbwiWbcJ8lAgD87KrcyW0xTiwMG0RWTmJRiV8JJAlun1ZLQFhKKDmsg6ff2kSICl1e1L9PZOpQuCB8n8tGb7i5oATonZZsrJMXWOruTXfx01cKEabUmwI1F+Z1TscPCO0+UVuUEJ+LC/vaWqYVNwv57T78fH1+75iD5EydCcTqfNXU06Y/DTCP/mhKQ35R1XcKzswPb9fmtXqeRtpXbhXtIKGbi04Ee6FhGCPuH/aCqene3BIJVpquKgTLl7ULFTgkKDY/yZkKRu9oOtUMXYnQcT7EDfCv1pLGTxKYD9v3IBe0AE1zAQk9BQEJEr5Vn99kdKB1LzTIhbI0fDTvMiZ4WyxGu7CMHez4UKzRUs9XcLv+3SOaSoaS8tkfQpSMCCqvt/XiomlKJgoI4/2e3TPXfkzfOaHeHVu+qM0uccyin5oPknPUsLzfe0OZ+GFZVsu7AggqIhawm/LCknnXBEivzk6xiR9fcomUs0ieujqulBBPwCF/HZkEO15pGO6B8eUHadJizn6WBCyrPh7XhsyAqdwSH08Owi74f95POcnaECUvyOrbrL9rDVroyNCVBAixRW+DTjCKVu16HbtvP0/KJjrP7O032cRSfATqUQMPBagH2xj/KcEYsMW7kWoVYVmJomuAvIjxbByf7DA86+VFMAofI9iuAf/Pudyx6x/KEGAi/DCNdHgf839TzPS9NXfvNTEuci2FmOAdLbQIgakesYXIjMEjnFmt4+Jwe5wjJ2hxhK+cfANfCxhsQDerahRlbJ8rMtqAsthcIZC1j+SkPGQuB13pJMXgyV6lWfw0O3j7+bZoUlQZjFGrchFpgQ0gilj+6xgbjKhe52zH7BRfy1vfadyNu8u8FyY3CQkCPJk8nnYL1kPX6/5R2UPOEQb/8YX4stjEWs8PWIWbfBS7b5h5ay2X5PSvGGTr4s+u+SfnByJ+ye5Rse6CWWUNfSQU9EGTCnCVZcAmRyFnUWljs32BLXaE4Am5kbGiNIa/pqx9bTY8djsmWN/Ou+aNC1TMI9bWqxyLZaM/prsSHwrdvqIuTPEi1S2kT4qX2dPL9ZmFJWWo7X1Bp/w3jQoFRcpELyOml1mLCAtNjF9ROYsq4xOo06SRUxwRRtn4S+XudSk5t+HLKkWnAj8f+VIIjexKz4aasm+X6Ynpjy47kqOrZXZtEow7il7kxkAAPzLqYShyM/AwcpoaDFC62QbZ//BS7fQOxp7nEE0C3s4CToiKgYXz8+/xRKIl4PRBF9cjf/o0CwezQh8BK9029DMG6MWlzWw+Uy6/MvYHC0h16FU0FnH9Fu9vFHgmg8WqgFTn8A1B+NOcb3crb18pib4fVCdGZI=">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'managed',
            cNounce: '35957',
            cRay: '77816379cc6722a3',
            cHash: '96ffa234eb3a409',
            cUPMDTk: "\/api\/auth\/session?__cf_chl_tk=mgs1BQ5KlKESXXXXXXXXXXXXXXXXXXXXXX794930-0-gaNycGzNEpE",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9jaGF0Lm9wZW5haS5jb2XXXXXXXXXXXXXXXXXXXXVzc2lvbg==',
                ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXwNy4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMDcuMC4xNDE4LjYy',
                rm: 'R0VU',
                d: 'KufDIwHzPls+2diuK5QVcaCCerde9UWH7IgMBN3lwfsd4oaT0WhDZXXXXXXXXXXXXXXXXXXXXXXXXXXXeh4JDltOmIZAYn0hX2pJ2BYI4oM7MeEF7jCPkkJs+Y5qrXT0DJaXRxkPhUhkY5rAK7G6L8I613PwZ1T6ym5YF47zHtGV6mMJbwm2gL5TST9BcPTkhz5htm7TGMpAGTCiX3FBPjUDGDIJxM2QK80woSDLxfvTIGVRBSz9mnp97vY6dzUvSXv0Yz4w8g1qDsF7x8Z6bnCDdfRJCgGLKfZPd9IYr9xcga1/wcx5ZzbDcynC4NVym6h7P3dMrtXF+BzNSM3Cz69bxpixkd49MmhoKvix3O1T2WSeNPdg7y9+UR3zJtyDHv7J4LRIV9IqNfRVqpCrovM4nCLOm4uHVCaTa/cWsP2xaX0ieRA8ZvgVzrG+Kq5FoNeSSO1+vZmtmIDkewKUDtHhToQyh6wnaPZtYEJV5APKm4L5S3WATqV/JXLw3WMfewrxbGQt0ahaZdNEQCLJc3JtgQgih0gsirYXMWuGDW7Affr1d7NyEgtjEcCGUmenB+4f006I6Tu83jm9eus3CDssKiRW5h',
                t: 'MTY3MDcXXXXXXXXXXDgwMDA=',
                m: '6HExaW7cS4o262fnzyVoXXXXXXXXXXXXXXX8cNCgDbAsaoY=',
                i1: 'r0WsKCon3RXXXXXXXXXXZ15Q==',
                i2: 'gB0guPr9JXXXXXXXXXXX5Mw==',
                zh: 'iuyN59AGNgeBFFXXXXXXXXCyd1dJnIVFAc=',
                uh: 'r8ReuYYD4T8V2FXXXXXXXXXXLL7XD565cQk=',
                hh: 'foaWmAUHGGlVCZaNUJIHhxzxFNzSPNnVe6rJjiQw728=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=77816379cc6722a3');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=77816379cc6722a3';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/auth\/session?__cf_chl_rt_tk=mgs1BQ5KlKESJXiyWb4j0yLXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXycGzNEpE" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>77816379cc6722a3</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
`

**Comment by fffiloni** [comment]
as reported [here](https://github.com/rawandahmad698/PyChatGPT/issues/112#issuecomment-1345673097) 

It's to do with and their (new) cloudflare hCaptcha implementation. Once you pass the security check, the browser stores a cf_clearance cookie which has a 1-year expiration. If this cookie is missing, even if you have a valid session/access token you will need to pass the security check again before accessing the website.

**Comment by fffiloni** [comment]
see also [this issue](https://github.com/transitive-bullshit/chatgpt-api/issues/96) to follow the ongoing discussions on solutions

**Comment by BooBooKittyFck** [comment]
> Hi. A temporary bypass using `undetected_chromedriver` is added to the new release v0.2.0. This library now requires a Chrome installation. Please check and let me know if you have any questions.

Works fine - only thing that would be lovely is when it would close the browser afterwards. 
When i call it via my bot it let the browser stay open.

**Comment by terry3041** [comment]
> > Hi. A temporary bypass using `undetected_chromedriver` is added to the new release v0.2.0. This library now requires a Chrome installation. Please check and let me know if you have any questions.
> 
> Works fine - only thing that would be lovely is when it would close the browser afterwards. When i call it via my bot it let the browser stay open.

Unfortunately, the browser window is required as Cloudflare will detect headless browser and the bypass will not work.

**Comment by BooBooKittyFck** [comment]
> > > Hi. A temporary bypass using `undetected_chromedriver` is added to the new release v0.2.0. This library now requires a Chrome installation. Please check and let me know if you have any questions.
> > 
> > 
> > Works fine - only thing that would be lovely is when it would close the browser afterwards. When i call it via my bot it let the browser stay open.
> 
> Unfortunately, the browser window is required as Cloudflare will detect headless browser and the bypass will not work.

I mean after the whole process is finished - the browser still stays open i mean something like self.driver.quit() after everything is done

**Comment by terry3041** [comment]
> I mean after the whole process is finished - the browser still stays open i mean something like self.driver.quit() after everything is done

That is achievable. But as we are ensuring auth every time when sending message, it means that we are going to init a new browser instance when using `send_message()`. That may be a little bit time consuming.
But if you dont mind, I can change that in the code.
https://github.com/terry3041/pyChatGPT/blob/441f714f171b5cc9acdac2556b647b468e20c0b1/src/pyChatGPT/pyChatGPT.py#L136

**Comment by BooBooKittyFck** [comment]
> > I mean after the whole process is finished - the browser still stays open i mean something like self.driver.quit() after everything is done
> 
> That is achievable. But as we are ensuring auth every time when sending message, it means that we are going to init a new browser instance when using `send_message()`. That may be a little bit time consuming. But if you dont mind, I can change that in the code.
> 
> https://github.com/terry3041/pyChatGPT/blob/441f714f171b5cc9acdac2556b647b468e20c0b1/src/pyChatGPT/pyChatGPT.py#L136

I just added self.driver.quit() in line 150 before it returns the msg - that will close the browser everytime and reopen a new session when i ask a new question ( actual use it in a discord bot ) 
Thanks alot for supporting terry!

**Comment by terry3041** [comment]
> > > I mean after the whole process is finished - the browser still stays open i mean something like self.driver.quit() after everything is done
> > 
> > 
> > That is achievable. But as we are ensuring auth every time when sending message, it means that we are going to init a new browser instance when using `send_message()`. That may be a little bit time consuming. But if you dont mind, I can change that in the code.
> > https://github.com/terry3041/pyChatGPT/blob/441f714f171b5cc9acdac2556b647b468e20c0b1/src/pyChatGPT/pyChatGPT.py#L136
> 
> I just added self.driver.quit() in line 150 before it returns the msg - that will close the browser everytime and reopen a new session when i ask a new question ( actual use it in a discord bot ) Thanks alot for supporting terry!

I have pushed version v0.2.3 to reduce the browser pop-up frequency. Please have a look and let me know if you have any questions.
