### ISSUE TITLE
AttributeError: 'ChatGPT' object has no attribute 'close'

### ISSUE THREAD

**Issue by iaston** [terry3041/pyChatGPT#60]
![image](https://user-images.githubusercontent.com/11807657/209210348-f260cd0d-fa87-42c3-b037-2d385fed6008.png)

pyChatGPT Version: 0.3.9.6

**Comment by mancunian1792** [comment]
You need to get the driver object and then call the close method. api1.driver.close() should work.

**Comment by terry3041** [comment]
Yeah I just removed the `close()` method in the latest commit.
Closing the python script normally should handle that.
