### ISSUE TITLE
is it possible to request with coversation id an parent id using requests?

### ISSUE THREAD

**Issue by Ulysses0817** [terry3041/pyChatGPT#64]
After logging into the chat page, maybe it's feasible to using requests.post() with cookies taken from selenium? I'm a little confused why didnt you implement it, hhhh. If so, I think that we must consider the ssl client fingerprint or any other cases?

**Comment by magicmars35** [comment]
+1  when the script that hold the API need to be restarted , a brand new conversation id is created everytime, and there is now no way to return in the contexte of the previous conversation before the restart

**Comment by terry3041** [comment]
> After logging into the chat page, maybe it's feasible to using requests.post() with cookies taken from selenium? I'm a little confused why didnt you implement it, hhhh. If so, I think that we must consider the ssl client fingerprint or any other cases?

That's what I did in earlier version. But TLS fingerprint is so troublesome that it does not work consistently.
Therefore, I have no way but to abandon this method.

> +1 when the script that hold the API need to be restarted , a brand new conversation id is created everytime, and there is now no way to return in the contexte of the previous conversation before the restart

#66 may help regarding this.
