### ISSUE TITLE
WebDriverException: Message: Service /root/.local/share/undetected_chromedriver/6504b73715fdea06_chromedriver unexpectedly exited. Status code was: -6

### ISSUE THREAD

**Issue by np-n** [terry3041/pyChatGPT#65]
I am trying to test the ChatGPT python wrapper and end up with the following error:
![image](https://user-images.githubusercontent.com/39429615/209303519-b54b98d0-55ab-4b29-b278-01f28a5466a6.png)
How to fix it? Thank you!

**Comment by terry3041** [comment]
Did you follow https://github.com/terry3041/pyChatGPT#how-do-i-get-it-to-work-on-google-colab?
