### ISSUE TITLE
Is there a way to bypass the 1 hour limit of messages sent?

### ISSUE THREAD

**Issue by mgrecopy** [terry3041/pyChatGPT#68]
I'm trying to get more responses but ChatGPT says that the 1-hour limit has been reached. I think that by refreshing the page this gets solved, but I don't know how. Or by refreshing the cookie (if there is a way to do this automatically please share). Any help would be nice. 

Thank you very much for developing this! Works really well!

**Comment by doevent** [comment]
Try limits: 30 requests per hour or wait 120 seconds between requests

**Comment by terry3041** [comment]
Other than creating new accounts, I don't think there are any ways to bypass the rate-limit.

**Comment by mgrecopy** [comment]
Ok, thanks for the reply sir.
