### ISSUE TITLE
Headless request stuck on 'Starting Browser'

### ISSUE THREAD

**Issue by zukixa** [terry3041/pyChatGPT#74]
Having had the issue as described in #62 - I've proceeded to setup an 22.04 Ubuntu Linux via Multipass shell, and have been attempting to run the code there.
However, after each attempt of running it, the system seems to get stuck on 'starting browser,' even though the Mac equivalent is able to go far beyond, but hangs at requests that are generating a prompt that is 'too long.'
I've done the chromium-browser installation as intended with xvfb

Mac:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/56563509/209722408-0d436fb7-5eb5-45d6-83c0-482cc647cfa6.png">
Linux:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/56563509/209722514-07614e17-d31a-4336-bbb6-8cb97f8243c7.png">

Code used:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/56563509/209722626-0bef3099-aeff-42ee-9902-ee89246f524b.png">

**Comment by terry3041** [comment]
> I've proceeded to setup an 22.04 Ubuntu Linux via Multipass shell, and have been attempting to run the code there. However, after each attempt of running it, the system seems to get stuck on 'starting browser,' 

I cannot reproduce this issue in a multipass shell environment. Maybe check your chrome installation in the multipass VM?

> Even though the Mac equivalent is able to go far beyond, but hangs at requests that are generating a prompt that is 'too long.'

Can you send me the question you asked?

**Comment by alotofkira** [comment]
1) Seems to be a chrome issue, chromium-browser doesn't even start in headless, and runs into a loop of "chromium not responding" if it starts with display mode -- even after an sudo apt upgrade/update? 

2) 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/56563509/209815460-8ae75ff3-1416-43c9-904b-f0879be2ac46.png">
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/56563509/209815505-7fd4ccf6-a0ec-48e1-8769-a618743009e7.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/56563509/209815539-8b6bbb1c-736f-4d74-80a9-3f7a1645df82.png">

**Comment by zukixa** [comment]
fun to look back at this when I still sucked at coding
in the end this was most likely just a "Multipass shell SUCKS" issue lol
