### ISSUE TITLE
New Model of ChatGPT

### ISSUE THREAD

**Issue by DoganK01** [terry3041/pyChatGPT#75]
Hello,

I want to change the "model" parameter in chatgpt. So I want to train my own model. How can I do it ?

**Comment by terry3041** [comment]
Sorry but I don't understand what you mean. Can you elaborate?

**Comment by Abdulsamipy** [comment]
@DoganK01 you need to create a conversation on chatgtpt website , train there and than add the conversation ID

**Comment by DoganK01** [comment]
Okey I figured it out. Many thanks.
