### ISSUE TITLE
vervify

### ISSUE THREAD

**Issue by Anxianx** [terry3041/pyChatGPT#9]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/57472822/206996687-68927c8e-9a26-4886-bbe4-590aa2f0eb21.png">

**Comment by terry3041** [comment]
Are you from China? Did you use VPN when using the library?
`undetected_chromedriver` needs to download chrome driver for the first time.
Maybe the website is blocked by the Great Wall
