### ISSUE TITLE
Error when initiate connection

### ISSUE THREAD

**Issue by Iamfinethanksu** [terry3041/pyChatGPT#95]
hi, the following errors happen when I try to authorize the ChatGPT connection with my session token using there following two lines:

session_token='whatever my session token'
api = ChatGPT(session_token)

The error msg are: 

DEBUG:pyChatGPT:Initializing browser...
DEBUG:pyChatGPT:Restoring session_token...
DEBUG:pyChatGPT:Ensuring Cloudflare cookies...
DEBUG:pyChatGPT:Opening new tab...
DEBUG:pyChatGPT:Getting Cloudflare challenge...
DEBUG:pyChatGPT:Cloudflare challenge passed
DEBUG:pyChatGPT:Validating authorization...
---------------------------------------------------------------------------
NoSuchElementException                    Traceback (most recent call last)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: chrome=108.0.5359.71)

Can someone help and give an explanations? Many thanks!

**Comment by ShahrukhAbrar** [comment]
Having the same issue. It was working properly till yesterday night so probably something change on ChatGPT side maybe?

**Comment by masanori0209** [comment]
I think it will probably work with the link below.

https://github.com/terry3041/pyChatGPT/issues/96#issuecomment-1372111419

**Comment by terry3041** [comment]
Explained in https://github.com/terry3041/pyChatGPT/issues/96#issuecomment-1374375008
